# Generated by Django 4.1.1 on 2022-09-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0007_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.SlugField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.CharField(default='2022 Sep 20', max_length=200),
        ),
    ]
